# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13CnlNEBWBrzEV8e23SxmdPtne1002u5Q
"""

import streamlit as st
import cv2
import numpy as np

st.title("🍃 Leaf Area Calculator")
st.write("Upload a photo of a leaf on the wooden piece.")

# 1. File Uploader (Works on iPhone camera/gallery)
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Convert uploaded file to OpenCV image
    file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=uint8)
    img = cv2.imdecode(file_bytes, 1)

    # 2. Pre-process
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    edged = cv2.Canny(blur, 75, 200)

    # 3. Find contours
    contours, _ = cv2.findContours(edged, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    contours = sorted(contours, key=cv2.contourArea, reverse=True)

    target_contour = None
    for c in contours:
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.02 * peri, True)
        if len(approx) == 4:
            target_contour = approx
            break

    if target_contour is None:
        st.error("Could not find the 4 corners of the wooden piece. Try a clearer photo.")
    else:
        # 4. Perspective Correction
        pts = target_contour.reshape(4, 2)
        rect = np.zeros((4, 2), dtype="float32")
        s = pts.sum(axis=1)
        rect[0] = pts[np.argmin(s)]
        rect[2] = pts[np.argmax(s)]
        diff = np.diff(pts, axis=1)
        rect[1] = pts[np.argmin(diff)]
        rect[3] = pts[np.argmax(diff)]

        dst = np.array([[0, 0], [400, 0], [400, 300], [0, 300]], dtype="float32")
        M = cv2.getPerspectiveTransform(rect, dst)
        warped = cv2.warpPerspective(img, M, (400, 300))

        # 5. Isolate Green Area
        hsv = cv2.cvtColor(warped, cv2.COLOR_BGR2HSV)
        lower_green = np.array([35, 40, 40])
        upper_green = np.array([90, 255, 255])
        mask = cv2.inRange(hsv, lower_green, upper_green)

        # 6. Calculate Area
        total_wood_pixels = warped.shape[0] * warped.shape[1]
        leaf_pixels = cv2.countNonZero(mask)
        leaf_area_sq_in = (leaf_pixels / total_wood_pixels) * 12.0

        # 7. Display Results
        st.success(f"Calculated Leaf Area: **{leaf_area_sq_in:.4f} sq inches**")

        # Display images side by side
        col1, col2 = st.columns(2)
        with col1:
            st.image(cv2.cvtColor(warped, cv2.COLOR_BGR2RGB), caption="Flattened Wood")
        with col2:
            st.image(mask, caption="Leaf Detection Mask")
